### ISSUE TITLE
swift 2 version.

### ISSUE THREAD

**Issue by kohdesmond** [okmr-d/DOAlertController#17]
swift 2 version.

**Comment by amorenew** [comment]
1+

**Comment by ghost** [comment]
+1

**Comment by misuqian** [comment]
You can just update by Xcode and edit a little

just like me :
https://github.com/misuqian/DOAlertController/blob/113c86cfb725cab3518807b4edc2ee2356e91104/DOAlertController/DOAlertController.swift
